Add ttf-dejavu, because of:
2019-03-18 09:03:24.559 ERROR [http-apr-8080-exec-8][PortletServlet:112] javax.portlet.PortletException: java.lang.NullPointerExceptio
n
javax.portlet.PortletException: java.lang.NullPointerException
at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCResourceCommand.serveResource(BaseMVCResourceCommand.java:49)
at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callResourceMethod(MVCPortlet.java:442) .......

Errors when navigating to 'Control Panel' -> 'Configuration' -> 'Server Administration'?